version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/var/www/app
    ports:
      - "8081:8081"
      - "5858:5858"
